# Generated by Django 4.0.5 on 2022-07-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='город')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='область')),
                ('slug', models.SlugField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'область',
                'verbose_name_plural': 'области',
            },
        ),
        migrations.CreateModel(
            name='Polyclinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='навание')),
                ('addres', models.CharField(max_length=100, verbose_name='адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон регистратуры')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='сайт')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinic_app.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'поликлиника',
                'verbose_name_plural': 'поликлиники',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyclinic_app.region', verbose_name='область'),
        ),
    ]
