# Generated by Django 4.0.5 on 2022-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='grodno', verbose_name='url'),
            preserve_default=False,
        ),
    ]
