# Generated by Django 4.0.5 on 2022-07-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0002_rename_phone_phonenumber_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polyclinic',
            old_name='url',
            new_name='site',
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='polyclinic_app.region', verbose_name='область'),
        ),
    ]
