# Generated by Django 4.0.5 on 2022-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0003_polyclinic_making_an_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polyclinic',
            old_name='addres',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='making_an_appointment',
            field=models.URLField(max_length=300, verbose_name='онлайн-запись'),
        ),
    ]
