# Generated by Django 4.0.5 on 2022-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0004_rename_addres_polyclinic_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyclinic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='навание'),
        ),
    ]
