# Generated by Django 4.0.5 on 2022-07-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0004_rename_site_polyclinic_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
    ]
