# Generated by Django 4.0.5 on 2022-07-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0007_polyclinic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='polyclinic_app.region', verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyclinic', to='polyclinic_app.city', verbose_name='город'),
        ),
    ]
