# Generated by Django 4.0.5 on 2022-07-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyclinic_app', '0008_rename_name_region_region_alter_city_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.AlterField(
            model_name='polyclinic',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polyclinics', to='polyclinic_app.city', verbose_name='город'),
        ),
    ]
